name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: standardbankpokemonregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker image
      run: docker build -t standardbankpokemonregistry.azurecr.io/pokemon .

    - name: Push Docker image to Azure Container Registry
      run: docker push standardbankpokemonregistry.azurecr.io/pokemon

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: standard-bank-pokemon-app
        images: 'standardbankpokemonregistry.azurecr.io/pokemon:latest'
        username: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_USERNAME }}
        password: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PASSWORD }}

